on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: test-action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: test-action
        uses: ./ # Uses an action in the root directory
        id: lizard
        with:
          path: "./src"
          language: "python"
          whitelist: "white text.txt"
      - name: Get the output time
        run: echo -e "${{ steps.lizard.outputs.result_output_path }}"
      - name: Get the output time
        run: ls
